### ISSUE TITLE
Segmentation Fault in your _LKH.main

### ISSUE THREAD

**Issue by gnana-sai-shipsy** [liangxinedu/NeuroLKH#1]
Running swig_test.py results in multiple python shell instances to open up. _LKH.main has this error `Segmentation Fault (Core dumped)` . Do help

**Comment by yzhang-gh** [comment]
I have also seen this issue. It can be solved by renaming the `main` function https://github.com/yzhang-gh/NeuroLKH/commit/05ff7de72dfba0bee2d03b0ce6bebee6a636e407

**Comment by gnana-sai-shipsy** [comment]
I see, so that means your fork of the repo is being maintained while this one isn't? 

Also I had another question (Do excuse me since they should be a separate issue)
* I ran using `make` it was working, it showed some numbers as a result for `LKH vs NeuroLKH` , but I don't quite understand what they mean..?
* In your CVRPTW extension code, is it possible to add custom cost functions & constraints? 


Thanks @yzhang-gh

**Comment by yzhang-gh** [comment]
This repo doesn't seem to be actively maintained, and I was just trying to replicate their experiments recently (so my understanding of the code may be limited).

The numbers compare the found tour length and running time of LKH and NeuroLKH, either under a given number of trials or under a time limit. (You can check Table 1 of the paper.)

As for the CVRPTW code, I didn't really look into it. If you are talking about the neural network part, it is adapted from https://github.com/chaitjo/graph-convnet-tsp as mentioned at the end of the `README`,

**Comment by gnana-sai-shipsy** [comment]
Great insights! Thank you! @yzhang-gh
