### ISSUE TITLE
an error ocurred in checkcall function  when run the test.py with the pretrained model

### ISSUE THREAD

**Issue by yourpower** [liangxinedu/NeuroLKH#6]
Dear liangxinedu,
    Thanks for your codeshare. When i run **the python3 test.py --dataset test/500.pkl --model_path pretrained/neurolkh.pt --n_samples 1000 --lkh_trials 1000 --neurolkh_trials 1000**, I encounter an error  in **check_call(['./LKH',para_filename], stdout=f)** as following, and i get confused because i cant find the dir ./LKH and its related .
Traceback (most recent call last):
  File "/mnt/e/MY/NeuroLKH-main/test.py", line 221, in <module>
    lkh_objs, lkh_runtimes, _, _ = eval_dataset(args.dataset, "LKH", args=args, rerun=True, max_trials=args.lkh_trials)
  File "/mnt/e/MY/NeuroLKH-main/test.py", line 206, in eval_dataset
    results = list(tqdm.tqdm(pool.imap(method_wrapper, [("LKH", dataset_name, dataset[i], str(i), rerun, max_trials) for i in range(len(dataset))]), total=len(dataset)))
  File "/home/zhangdekang/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: './LKH'

Thanks!

**Comment by liangxinedu** [comment]
Thank you for your interest in our work. 
Could you try to compile the code and check if there is an executable named "LKH"?
such as "mkdir SRC/OBJ; make"

**Comment by yourpower** [comment]
> Thank you for your interest in our work. Could you try to compile the code and check if there is an executable named "LKH"? such as "mkdir SRC/OBJ; make"

Thank you for all your answers
